name: Pulsarctl BookKeeper Unit Tests Check
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run bookKeeper service
      run: |
        pushd test/docker
        docker-compose pull
        docker-compose up -d
        popd
        sleep 10

    - name: Check bookKeeper service
      run: |
        docker ps
        ./test/script/check.sh bookie

    - name: Test
      run: |
        docker ps
        go test -v ./pkg/bkctl/...
        go test -v ./pkg/bookkeeper/...

