name: Pulsarctl
on:
  pull_request:
    branches:
    - '*'
    path-ignores:
    - 'docs/**'
    - 'README.md'
    - 'CONTRIBUTING.md'
jobs:
  auth-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "ossrh", "username": "${{ secrets.SONATYPE_USERNAME }}",
          "password": "${{ secrets.SONATYPE_PASSWORD }}"}]'
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
    - uses: actions/checkout@v2
    - name: Run token tests
      run: scripts/run-integration-tests.sh token
    - name: Run TLS tests
      run: scripts/run-integration-tests.sh tls
