name: Pulsarctl
on:
  pull_request:
    branches:
    - '*'
    path-ignores:
    - docs/**
    - README.md
    - CONTRIBUTING.md
jobs:
  auth-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run token tests
      run: scripts/run-integration-tests.sh token
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Run TLS tests
      run: scripts/run-integration-tests.sh tls
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
