name: Pulsarctl
on:
  pull_request:
    branches:
      - master
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
jobs:
  auth-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run token tests
        run: scripts/run-integration-tests.sh token
      - name: Run TLS tests
        run: scripts/run-integration-tests.sh tls
