name: Pulsarctl
on:
  pull_request:
    branches:
      - master
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
jobs:
  ut-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: scripts/run-integration-tests.sh
