name: Pulsarctl
on:
  pull_request:
    branches:
      - master
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
jobs:
  ut-tests:
    name:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v2
    - name: Run tests
      run: scripts/run-integration-tests.sh
