name: Pulsarctl
on:
  pull_request:
    branches:
    - '*'
    path-ignores:
    - docs/**
    - README.md
    - CONTRIBUTING.md
jobs:
  ut-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - uses: actions/checkout@v2
    - name: Run tests
      run: scripts/run-integration-tests.sh
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
