name: Pulsarctl
on:
  pull_request:
    branches:
      - '*'
    path-ignores:
      - 'docs/**'
      - 'README.md'
      - 'CONTRIBUTING.md'
jobs:
  ut-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Login SN docker hub
      run: docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASSWORD}}"
    - uses: actions/checkout@v2
    - name: Run tests
      run: scripts/run-integration-tests.sh
