name: Pulsarctl Pulsar Cluster Tests Check
on: [pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run Pulsar cluster service
      run: |
        pushd test/docker
        docker-compose -f pulsar-cluster.yml up -d
        popd

    - name: Check Pulsar cluster service
      run: |
        ./test/script/check.sh HTTP

    - name: Preapare for functions, sources, and sinks
      run: |
        wget -P test/sources https://archive.apache.org/dist/pulsar/pulsar-2.4.0/connectors/pulsar-io-kafka-2.4.0.nar
        wget -P test/sinks https://archive.apache.org/dist/pulsar/pulsar-2.4.0/connectors/pulsar-io-jdbc-2.4.0.nar
        docker cp test/sources/pulsar-io-kafka-2.4.0.nar broker:/pulsar
        docker cp test/sinks/pulsar-io-jdbc-2.4.0.nar broker:/pulsar
        docker cp test/sources/kafkaSourceConfig.yaml broker:/pulsar/conf
        docker cp test/sinks/mysql-jdbc-sink.yaml broker:/pulsar/conf
        docker cp broker:/pulsar/examples/api-examples.jar test/functions

    - name: Test
      run: |
        docker ps
        go test -v $(go list ./... | grep -v bookkeeper | grep -v bkctl)
