name: Test Install script
on:
  pull_request:
    branches:
      - master
    paths:
      - 'install.sh'
      - 'stable.txt'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test install
      run: |
        ./install.sh -u -v v0.3.0
        ~/.pulsarctl/pulsarctl help
        ./install.sh -u
        ~/.pulsarctl/pulsarctl help
