name: Release

on:
  pull_request:
    branches: 
      - zymap-test-release
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: release
      run: go build .
    - name: release note
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
    
    - name: Upload
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      with:
        args: 'pulsarctl'
