name: test-ci-test-1
on: 
  push:
    branches: 
      - test-ci-1
  pull_request:
    branches: 
      - test-ci-1
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: test hello
        run: |
          echo "hello world"

