name: test-ci
on:
  push:
    branches:
      - test-ci
  pull_request:
    branches:
      - test-ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.12
        run: |
          echo "hello world"

